[package]
name = "test-crate"
version = "0.1.0"
edition = "2021"
authors = [""]

[dependencies]
ctru-rs = { git = "https://github.com/Meziu/ctru-rs.git" }
ctru-sys = { git = "https://github.com/Meziu/ctru-rs.git" }
