name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        toolchain:
          # Oldest supported nightly
          - nightly-2024-02-18
          - nightly
        ctru-rs-ref:
          # "known good" version of `test-runner` crate
          - 3247af67d5f9aafb0ea4af485a81b74ce922c8af
          - master

    continue-on-error: ${{ matrix.toolchain == 'nightly' || matrix.ctru-rs-ref == 'master' }}
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitarm
      volumes:
        # So the test action can `docker run` the runner:
        - '/var/run/docker.sock:/var/run/docker.sock'
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - uses: ./setup
        with:
          toolchain: ${{ matrix.toolchain }}

      - uses: actions/checkout@v4
        with:
          repository: 'rust3ds/ctru-rs'
          path: 'ctru-rs'
          ref: ${{ matrix.ctru-rs-ref }}

      - name: Build and run tests (unit + integration)
        uses: ./run-tests
        with:
          working-directory: ctru-rs
          args: --package test-runner -- -v

      - name: Build and run doc tests
        # Still run doc tests even if lib/integration tests fail:
        if: ${{ !cancelled() }}
        env:
          # This ensures the citra logs and video output get persisted to a
          # directory where the artifact upload can find them.
          RUSTDOCFLAGS: " --persist-doctests target/armv6k-nintendo-3ds/debug/doctests"
        uses: ./run-tests
        with:
          working-directory: ctru-rs
          args: --doc --package test-runner -v

      - name: Upload citra logs and capture videos
        uses: actions/upload-artifact@v3
        # We always want to upload artifacts regardless of previous success/failure
        if: ${{ !cancelled() }}
        with:
          name: citra-logs-${{ matrix.toolchain }}
          path: |
            ctru-rs/target/armv6k-nintendo-3ds/debug/**/*.txt
            ctru-rs/target/armv6k-nintendo-3ds/debug/**/*.webm
